#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Litstack\Lang\LangCheckCommand;
use Litstack\Lang\LangUpdateReadmeCommand;

if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

$container = new Illuminate\Container\Container;
$dispatcher = new Illuminate\Events\Dispatcher;
$files = new Illuminate\Filesystem\Filesystem;

$version = '8.0'; // Laravel version

$app = new Illuminate\Console\Application(
    $container, $dispatcher, $version
);

$app->add(new LangCheckCommand($files));
$app->add(new LangUpdateReadmeCommand($files));

$app->run();
